### ISSUE TITLE
Slug is not getting compiled

### ISSUE THREAD

**Issue by xxsimoxx** [KTS915/Test-ClassicPress-Directory#17]
When submitting a plugin the `slug` meta seems to remain empty.

**Comment by xxsimoxx** [comment]
Seems it depends on the ZIP file.
Using https://github.com/azurecurve/azrcrv-avatars/releases/download/v2.1.1/azrcrv-avatars.zip 
[Here](https://github.com/KTS915/Test-ClassicPress-Directory/blob/dccdef340b627a3e15d6ae45987bc65d2f724725/mu-plugins/software-submit-form.php#L380) for that plugin should be `$dir = trim( $zip->getNameIndex(22), '/' );` and anyway `$dir` is `azrcrv-avatars/azrcrv-avatars.php` and `$slug` is just `azrcrv-avatars`.

**Comment by KTS915** [comment]
Hmm, I'm wondering if we're at cross-purposes here. The slug should indeed be `azrcrv-avatars`. That's the name of the top-level folder of the plugin, which is what "slug" means in this context. So I think some of the associated PR can probably be deleted as unnecessary.

**Comment by xxsimoxx** [comment]
I was thinking at the slug as in Update Manager, so `azrcrv-avatars/azrcrv-avatars.php` so closing this as it's not an issue.
