### ISSUE TITLE
Remove Gravatars

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#2]
For privacy, we should consider removing Gravatars. If an avatar is needed, we should consider adding local avatars:
https://directory.classicpress.net/plugins/avatars

**Comment by KTS915** [comment]
I'm happy to do that but, if we're going to use avatars at all, I have my own avatars plugin that I much prefer and use on many of my sites. It uses an earlier filter and so is much more efficient, as well as providing a built-in SVG letter fallback.

The question really is whether we want to have avatars at all.

**Comment by viktorix** [comment]
It's probably more of an aesthetic choice. Since it represents a developer/brand, it could be their logo, and it could be shown on their public page as well as an icon on plugin/theme pages to make it looks visually pleasing. 

Your avatar plugin is good, too.

**Comment by xxsimoxx** [comment]
+1 for your avatar plugin.

**Comment by KTS915** [comment]
Addressed by above commit and associated mods.

**Comment by viktorix** [comment]
Works.
