### ISSUE TITLE
How much software info should get updated by the daily cronjob?

### ISSUE THREAD

**Issue by KTS915** [KTS915/Test-ClassicPress-Directory#23]
Following on the discussion from Issue #8, I'm wondering how much information should get updated by the daily cronjob from the Directory to each GitHub repo to check on each piece of software. I'm concerned about overwhelming the Directory. At the moment, I have put a five-second `sleep()` in place in the `mu-plugins -> download-links.php` file, but I still think trying to update everything might be too much.

Would it be enough to update everything only when the developer hits the button to do it manually?

**Comment by xxsimoxx** [comment]
> Would it be enough to update everything only when the developer hits the button to do it manually?

I'm all for this. And doing it the same way (checking the API from GitHub and fetching the new zip...) it is done in `software-submit-form.php`.
Maybe using the same function for both, so if you are going to fetch more data, add more controls ecc... this is done only in one place.

**Comment by KTS915** [comment]
Thinking about thus further, I wonder if we're approaching it the wrong way round. Maybe we should run a much more frequent cronjob  (say, every 10 minutes) but only update one or two softwares at a time.

**Comment by xxsimoxx** [comment]
I still can't get a clear idea of what the best solution might be. Luckily, it is something that can be adjusted over time based on the number of plugins.
I'm pretty convinced about one thing, though. We should have a `maybe_update ( $item_id )` function that is used both by the `kts_cron_update_download_links` and `kts_software_update_link_redirect` functions.
This way duplicated code is avoided and we can use the function also, as an example, in a `wp-cli` command.

**Comment by xxsimoxx** [comment]
My proposal for `maybe_update` function in #25.

**Comment by KTS915** [comment]
Great, thanks! Now merged.

**Comment by KTS915** [comment]
I am thinking now that, in principle, a more frequent cronjob, updating only one or two softwares, is indeed the way to go. We could do this using the round robin method. But there's a practical problem. We would need somewhere to store all the software details for the round robin.

That "blob" of information would be much too large for the `options` table. Maybe we need a dedicated custom database table.

**Comment by xxsimoxx** [comment]
We can also just query as example for 2 CPT ordered by `modified`. 
Then if the last modified time is too recent just skip it.
If it is not skipped do the check and update the last modified date even if there are not updates.

**Comment by KTS915** [comment]
Of course! Yes, that's the way to do it. OK, I'll work on that. Thanks!

**Comment by KTS915** [comment]
Addressed by above commit and PR #26
