### ISSUE TITLE
GitHub username not editable

### ISSUE THREAD

**Issue by xxsimoxx** [KTS915/Test-ClassicPress-Directory#31]
In the profile page the GitHub username is not editable by an administrator.
I understand that a developer (contributor role) can't edit this for security reasons but an admin should be able to do this without using command line.
Please check this issue because I can only check this from my phone.

**Comment by KTS915** [comment]
Confirmed. Addressed by above and subsequent commit.

**Comment by xxsimoxx** [comment]
Don't know if i'm having problem being on mobile, but it is not saving the new value.

**Comment by KTS915** [comment]
If the new username is not associated with a GitHub repo, then it won't save.

**Comment by xxsimoxx** [comment]
Great! Thank you!
