### ISSUE TITLE
Broken images in README.md (feedback request)

### ISSUE THREAD

**Issue by xxsimoxx** [KTS915/Test-ClassicPress-Directory#39]
If the `README.md` contains images with relative paths, when the markdown file is rendered is broken.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/29772709/189685460-953b512b-8709-437d-9d20-15825ccaadfe.png">

We can just consider this as a normal behavior and close this issue.

Otherwise, I could adapt a snippet that does something similar (that I use on a client site) to do that.
The trick is done in JavaScript and works on images that are not loaded properly.

**Comment by KTS915** [comment]
Yes, I had noticed that but, with the new semester starting, haven't had time to address it. I'm happy for you to propose something, especially as you've already tested it elsewhere!
