### ISSUE TITLE
Remove personal options from profile.php

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#4]
To clean things up and keep it to the point, developers don't need personal options in this case. We should remove them, so only fields we actually use are left on the profile page.
![image](https://user-images.githubusercontent.com/1692600/180306319-02ab9c4f-b571-4128-87a3-a4c24f6425fe.png)

**Comment by KTS915** [comment]
Now done in `mu-plugins` -> `registration-users.php` line 248

**Comment by viktorix** [comment]
@KTS915 do we need these personal options for developers?
![image](https://user-images.githubusercontent.com/1692600/180807004-5471e96c-83ed-45df-a65e-a3d975b98861.png)

**Comment by KTS915** [comment]
No. I have them on my list to hide. Would like to find a PHP hook to not show them rather than just use CSS, but haven't had time to look for the hook yet. Do you happen to know it ( or if there is one)?

**Comment by xxsimoxx** [comment]
For me is good disabling by default the visual editor as:
- in plugin full description maybe just markdown can be used.
- in writing review HTML markup don't work.

**Comment by viktorix** [comment]
See if this works:
```

  // removes admin color scheme options
    remove_action( 'admin_color_scheme_picker', 'admin_color_scheme_picker' );

    if ( ! function_exists( 'cor_remove_personal_options' ) ) {
        /**
        * Removes the leftover 'Visual Editor', 'Keyboard Shortcuts' and 'Toolbar' options.
        */
        function cor_remove_personal_options( $subject ) {
            $subject = preg_replace( '#<h2>Personal Options</h2>.+?/table>#s', '', $subject, 1 );
            return $subject;
        }

        function cor_profile_subject_start() {
            ob_start( 'cor_remove_personal_options' );
        }

        function cor_profile_subject_end() {
            ob_end_flush();
        }
    }
    add_action( 'admin_head', 'cor_profile_subject_start' );
    add_action( 'admin_footer', 'cor_profile_subject_end' );
```

[Source with more examples](https://wordpress.stackexchange.com/a/229014)

**Comment by KTS915** [comment]
I never use the rich text editor myself, and always disable it on my own sites, so I'm happy to do the same here, @xxsimoxx. Thanks for that code, @viktorix. It needed a few tweaks (one to get it working, and others so that it doesn't load on every admin page) but it set me on the right path.

Both issues now addressed with above commit.
