### ISSUE TITLE
Hide 2FA notice when it is activated

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#5]
I just activated 2FA, but the notice is still there. Refreshing doesn't help. Maybe you haven't added a conditional check yet.
![image](https://user-images.githubusercontent.com/1692600/180308174-4ae1a6cc-a13e-47e8-b3ba-bd535ecf91cf.png)

**Comment by KTS915** [comment]
Addressed by above commits.
