### ISSUE TITLE
Provide relevant message/feedback based on where developer is in the process

### ISSUE THREAD

**Issue by viktorix** [KTS915/Test-ClassicPress-Directory#6]
Maybe this is something you're still working on, so you can ignore this. 

1. When 2FA is activated, the 2FA notice should go away and we need to provide a new notice "Your account is pending review. You will receive an email when you have been approved." on the profile.php page.
2. On the form pages in the frontend, we should also cater the message based on where developer is in the approval process. Right now, my 2FA is activated but the form pages still say:

> You must be approved before you can submit software for review.
> 
> IMPORTANT: Before you can be approved, you must go to your [profile page and activate 2-Factor Authentication](https://test-directory.webby-books.com/wp-admin/profile.php#two-factor-options).
> 
> You will receive an email when you have been approved.

We should hide " IMPORTANT: Before you can be approved, you must go to your [profile page and activate 2-Factor Authentication](https://test-directory.webby-books.com/wp-admin/profile.php#two-factor-options)." when 2FA is activated:

> Your account is pending review and must be approved before you can submit software for review and listing.
 You will receive an email when you have been approved.

We should keep this in mind wherever else we're doing this.

**Comment by KTS915** [comment]
Yes, these are good points.

**Comment by KTS915** [comment]
Just needed to find the relevant code to use from the Two Factor plugin. Now found it and tested that I have it right. Will work on these and the other issues over the weekend. And thanks for the proposed wording!

**Comment by KTS915** [comment]
Addressed via above commits.
